// Generated by https://quicktype.io
class Productos {
  List<Producto> items = new List();

  Productos();

  Productos.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    for (var item in jsonList) {
      print(item);
      final producto = new Producto.fromJasonMap(item);
      items.add(producto);
    }
  }
}

class Producto {
  int id;
  String name;
  int price;
  String urlImage;

  Producto({
    this.id,
    this.name,
    this.price,
    this.urlImage,
  });

  Producto.fromJasonMap(Map<String, dynamic> json) {
    id = json["id"] / 1;
    name = json["name"];
    price = json["price"] / 1;
    urlImage = json["urlImage"];
  }
}
